export type BakedAsset = { symbol: string; name: string; coingeckoId: string; decimals: number; rank: number; coinbasePair?: string; binancePair?: string };

export const BAKED_TOP_100: BakedAsset[] = [
  { symbol: "BTC", name: "Bitcoin", coingeckoId: "bitcoin", decimals: 8, rank: 1, coinbasePair: "BTC-USD", binancePair: "BTCUSDT" },
  { symbol: "ETH", name: "Ethereum", coingeckoId: "ethereum", decimals: 6, rank: 2, coinbasePair: "ETH-USD", binancePair: "ETHUSDT" },
  { symbol: "USDT", name: "Tether", coingeckoId: "tether", decimals: 3, rank: 3 },
  { symbol: "BNB", name: "Binance Coin", coingeckoId: "binancecoin", decimals: 4, rank: 4 },
  { symbol: "USDC", name: "USD Coin", coingeckoId: "usd-coin", decimals: 3, rank: 5, coinbasePair: "USDC-USD", binancePair: "USDCUSDT" },
  { symbol: "XRP", name: "XRP", coingeckoId: "ripple", decimals: 3, rank: 6, coinbasePair: "XRP-USD", binancePair: "XRPUSDT" },
  { symbol: "SOL", name: "Solana", coingeckoId: "solana", decimals: 4, rank: 7, coinbasePair: "SOL-USD", binancePair: "SOLUSDT" },
  { symbol: "TRX", name: "TRON", coingeckoId: "tron", decimals: 3, rank: 8, coinbasePair: "TRX-USD", binancePair: "TRXUSDT" },
  { symbol: "HYPE", name: "Hyperliquid", coingeckoId: "hyperliquid", decimals: 4, rank: 9 },
  { symbol: "STETH", name: "Staked Ether", coingeckoId: "staked-ether", decimals: 6, rank: 10 },
  { symbol: "USDE", name: "Ethena USDe", coingeckoId: "ethena-usde", decimals: 3, rank: 11 },
  { symbol: "DOGE", name: "Dogecoin", coingeckoId: "dogecoin", decimals: 2, rank: 12, coinbasePair: "DOGE-USD", binancePair: "DOGEUSDT" },
  { symbol: "ZEC", name: "Zcash", coingeckoId: "zcash", decimals: 4, rank: 13, coinbasePair: "ZEC-USD" },
  { symbol: "WBTC", name: "Wrapped Bitcoin", coingeckoId: "wrapped-bitcoin", decimals: 8, rank: 14 },
  { symbol: "WBETH", name: "Wrapped Beacon ETH", coingeckoId: "wrapped-beacon-eth", decimals: 6, rank: 15 },
  { symbol: "XMR", name: "Monero", coingeckoId: "monero", decimals: 4, rank: 16, coinbasePair: "XMR-USD" },
  { symbol: "WETH", name: "WETH", coingeckoId: "weth", decimals: 6, rank: 17 },
  { symbol: "LINK", name: "ChainLink", coingeckoId: "chainlink", decimals: 4, rank: 18, coinbasePair: "LINK-USD", binancePair: "LINKUSDT" },
  { symbol: "ADA", name: "Cardano", coingeckoId: "cardano", decimals: 3, rank: 19, coinbasePair: "ADA-USD", binancePair: "ADAUSDT" },
  { symbol: "XLM", name: "Stellar", coingeckoId: "stellar", decimals: 3, rank: 20, coinbasePair: "XLM-USD", binancePair: "XLMUSDT" },
  { symbol: "DAI", name: "Dai", coingeckoId: "dai", decimals: 3, rank: 21, coinbasePair: "DAI-USD" },
  { symbol: "TON", name: "TON Coin", coingeckoId: "the-open-network", decimals: 3, rank: 22, coinbasePair: "TON-USD", binancePair: "TONUSDT" },
  { symbol: "BCH", name: "Bitcoin Cash", coingeckoId: "bitcoin-cash", decimals: 4, rank: 23, coinbasePair: "BCH-USD", binancePair: "BCHUSDT" },
  { symbol: "LTC", name: "Litecoin", coingeckoId: "litecoin", decimals: 4, rank: 24, coinbasePair: "LTC-USD", binancePair: "LTCUSDT" },
  { symbol: "HBAR", name: "Hedera Hashgraph", coingeckoId: "hedera-hashgraph", decimals: 2, rank: 25, coinbasePair: "HBAR-USD", binancePair: "HBARUSDT" },
  { symbol: "AVAX", name: "Avalanche", coingeckoId: "avalanche-2", decimals: 3, rank: 26, coinbasePair: "AVAX-USD", binancePair: "AVAXUSDT" },
  { symbol: "SHIB", name: "Shiba Inu", coingeckoId: "shiba-inu", decimals: 0, rank: 27, coinbasePair: "SHIB-USD", binancePair: "SHIBUSDT" },
  { symbol: "SUI", name: "Sui", coingeckoId: "sui", decimals: 3, rank: 28, coinbasePair: "SUI-USD", binancePair: "SUIUSDT" },
  { symbol: "UNI", name: "Uniswap", coingeckoId: "uniswap", decimals: 3, rank: 29, coinbasePair: "UNI-USD", binancePair: "UNIUSDT" },
  { symbol: "NEAR", name: "NEAR Protocol", coingeckoId: "near", decimals: 3, rank: 30, coinbasePair: "NEAR-USD", binancePair: "NEARUSDT" },
  { symbol: "OKB", name: "OKB", coingeckoId: "okb", decimals: 4, rank: 31 },
  { symbol: "TAO", name: "Bittensor", coingeckoId: "bittensor", decimals: 4, rank: 32, coinbasePair: "TAO-USD", binancePair: "TAOUSDT" },
  { symbol: "XAUT", name: "Tether Gold", coingeckoId: "tether-gold", decimals: 6, rank: 33 },
  { symbol: "BFUSD", name: "BFUSD", coingeckoId: "bfusd", decimals: 3, rank: 34 },
  { symbol: "MKR", name: "Maker", coingeckoId: "maker", decimals: 6, rank: 35, coinbasePair: "MKR-USD" },
  { symbol: "MUMU", name: "Mumu the Bull (SOL)", coingeckoId: "mumu-the-bull", decimals: 0, rank: 36 },
  { symbol: "WLFI", name: "World Liberty Financial", coingeckoId: "world-liberty-financial", decimals: 2, rank: 37 },
  { symbol: "MNT", name: "Mantle", coingeckoId: "mantle", decimals: 3, rank: 38 },
  { symbol: "AAVE", name: "Aave", coingeckoId: "aave", decimals: 4, rank: 39, coinbasePair: "AAVE-USD", binancePair: "AAVEUSDT" },
  { symbol: "PYUSD", name: "PayPal USD", coingeckoId: "paypal-usd", decimals: 3, rank: 40 },
  { symbol: "PAXG", name: "PAX Gold", coingeckoId: "pax-gold", decimals: 6, rank: 41 },
  { symbol: "ICP", name: "Internet Computer (IOU)", coingeckoId: "internet-computer", decimals: 3, rank: 42, coinbasePair: "ICP-USD" },
  { symbol: "BGB", name: "Bitget Token", coingeckoId: "bitget-token", decimals: 3, rank: 43 },
  { symbol: "PEPE", name: "Pepe", coingeckoId: "pepe", decimals: 0, rank: 44, coinbasePair: "PEPE-USD", binancePair: "PEPEUSDT" },
  { symbol: "DOT", name: "Polkadot", coingeckoId: "polkadot", decimals: 3, rank: 45, coinbasePair: "DOT-USD", binancePair: "DOTUSDT" },
  { symbol: "FDUSD", name: "First Digital USD", coingeckoId: "first-digital-usd", decimals: 3, rank: 46 },
  { symbol: "BNSOL", name: "Binance Staked SOL", coingeckoId: "binance-staked-sol", decimals: 4, rank: 47 },
  { symbol: "ONDO", name: "Ondo", coingeckoId: "ondo-finance", decimals: 3, rank: 48, coinbasePair: "ONDO-USD" },
  { symbol: "ASTER", name: "Aster", coingeckoId: "aster-2", decimals: 3, rank: 49 },
  { symbol: "JST", name: "JUST", coingeckoId: "just", decimals: 3, rank: 50 },
  { symbol: "ETC", name: "Ethereum Classic", coingeckoId: "ethereum-classic", decimals: 3, rank: 51, coinbasePair: "ETC-USD", binancePair: "ETCUSDT" },
  { symbol: "MATIC", name: "Matic Network", coingeckoId: "matic-network", decimals: 3, rank: 52, coinbasePair: "MATIC-USD" },
  { symbol: "WBNB", name: "Wrapped BNB", coingeckoId: "wbnb", decimals: 4, rank: 53 },
  { symbol: "MORPHO", name: "Morpho", coingeckoId: "morpho", decimals: 3, rank: 54 },
  { symbol: "WLD", name: "Worldcoin", coingeckoId: "worldcoin-wld", decimals: 3, rank: 55, coinbasePair: "WLD-USD", binancePair: "WLDUSDT" },
  { symbol: "PI", name: "Pi", coingeckoId: "pi-network", decimals: 2, rank: 56 },
  { symbol: "RLUSD", name: "Ripple USD", coingeckoId: "ripple-usd", decimals: 3, rank: 57 },
  { symbol: "ALGO", name: "Algorand", coingeckoId: "algorand", decimals: 2, rank: 58, coinbasePair: "ALGO-USD" },
  { symbol: "KAS", name: "Kaspa", coingeckoId: "kaspa", decimals: 2, rank: 59 },
  { symbol: "RENDER", name: "Render", coingeckoId: "render-token", decimals: 3, rank: 60, coinbasePair: "RENDER-USD", binancePair: "RENDERUSDT" },
  { symbol: "QNT", name: "Quant", coingeckoId: "quant-network", decimals: 4, rank: 61, coinbasePair: "QNT-USD" },
  { symbol: "ATOM", name: "Cosmos", coingeckoId: "cosmos", decimals: 3, rank: 62, coinbasePair: "ATOM-USD", binancePair: "ATOMUSDT" },
  { symbol: "USDG", name: "Global Dollar", coingeckoId: "global-dollar", decimals: 3, rank: 63 },
  { symbol: "ENA", name: "Ethena", coingeckoId: "ethena", decimals: 2, rank: 64, binancePair: "ENAUSDT" },
  { symbol: "STABLE", name: "Stable", coingeckoId: "stable", decimals: 2, rank: 65 },
  { symbol: "KCS", name: "KuCoin Shares", coingeckoId: "kucoin-shares", decimals: 3, rank: 66 },
  { symbol: "BDX", name: "Beldex", coingeckoId: "beldex", decimals: 2, rank: 67 },
  { symbol: "CAKE", name: "PancakeSwap", coingeckoId: "pancakeswap-token", decimals: 3, rank: 68 },
  { symbol: "VVV", name: "Venice Token", coingeckoId: "venice-token", decimals: 4, rank: 69 },
  { symbol: "USDD", name: "USDD", coingeckoId: "usdd", decimals: 3, rank: 70 },
  { symbol: "TUSD", name: "TrueUSD", coingeckoId: "true-usd", decimals: 3, rank: 71 },
  { symbol: "NEXO", name: "Nexo", coingeckoId: "nexo", decimals: 3, rank: 72 },
  { symbol: "ARB", name: "Arbitrum", coingeckoId: "arbitrum", decimals: 2, rank: 73, coinbasePair: "ARB-USD", binancePair: "ARBUSDT" },
  { symbol: "FLR", name: "Flare", coingeckoId: "flare-networks", decimals: 0, rank: 74 },
  { symbol: "FIL", name: "Filecoin", coingeckoId: "filecoin", decimals: 3, rank: 75, coinbasePair: "FIL-USD", binancePair: "FILUSDT" },
  { symbol: "CRO", name: "Crypto.com Chain", coingeckoId: "crypto-com-chain", decimals: 2, rank: 76, coinbasePair: "CRO-USD" },
  { symbol: "INJ", name: "Injective Protocol", coingeckoId: "injective-protocol", decimals: 3, rank: 77, coinbasePair: "INJ-USD", binancePair: "INJUSDT" },
  { symbol: "VET", name: "VeChain", coingeckoId: "vechain", decimals: 0, rank: 78, coinbasePair: "VET-USD" },
  { symbol: "PENGU", name: "Pudgy Penguins", coingeckoId: "pudgy-penguins", decimals: 0, rank: 79 },
  { symbol: "DASH", name: "Dash", coingeckoId: "dash", decimals: 4, rank: 80, coinbasePair: "DASH-USD" },
  { symbol: "VIRTUAL", name: "Virtual Protocol", coingeckoId: "virtual-protocol", decimals: 3, rank: 81 },
  { symbol: "APT", name: "Aptos", coingeckoId: "aptos", decimals: 3, rank: 82, coinbasePair: "APT-USD", binancePair: "APTUSDT" },
  { symbol: "AERO", name: "Aerodrome Finance", coingeckoId: "aerodrome-finance", decimals: 3, rank: 83 },
  { symbol: "CRV", name: "Curve DAO Token", coingeckoId: "curve-dao-token", decimals: 3, rank: 84, coinbasePair: "CRV-USD", binancePair: "CRVUSDT" },
  { symbol: "GHO", name: "GHO", coingeckoId: "gho", decimals: 3, rank: 85 },
  { symbol: "TRUMP", name: "OFFICIAL TRUMP", coingeckoId: "official-trump", decimals: 3, rank: 86 },
  { symbol: "SPX", name: "SPX6900", coingeckoId: "spx6900", decimals: 3, rank: 87 },
  { symbol: "FET", name: "Fetch.ai", coingeckoId: "fetch-ai", decimals: 3, rank: 88, coinbasePair: "FET-USD", binancePair: "FETUSDT" },
  { symbol: "XDCE", name: "XinFin Network", coingeckoId: "xdce-crowd-sale", decimals: 2, rank: 89 },
  { symbol: "GNO", name: "Gnosis", coingeckoId: "gnosis", decimals: 4, rank: 90 },
  { symbol: "CBETH", name: "Coinbase Wrapped Staked ETH", coingeckoId: "coinbase-wrapped-staked-eth", decimals: 6, rank: 91 },
  { symbol: "HEX", name: "HEX", coingeckoId: "hex", decimals: 0, rank: 92 },
  { symbol: "BCHSV", name: "Bitcoin SV", coingeckoId: "bitcoin-cash-sv", decimals: 4, rank: 93 },
  { symbol: "LDO", name: "Lido DAO", coingeckoId: "lido-dao", decimals: 3, rank: 94, coinbasePair: "LDO-USD", binancePair: "LDOUSDT" },
  { symbol: "FRAX", name: "Frax", coingeckoId: "frax", decimals: 3, rank: 95 },
  { symbol: "NFT", name: "APENFT", coingeckoId: "apenft", decimals: 0, rank: 96 },
  { symbol: "LUNC", name: "Terra Classic", coingeckoId: "terra-luna", decimals: 0, rank: 97 },
  { symbol: "ETHFI", name: "ether.fi", coingeckoId: "ether-fi", decimals: 3, rank: 98 },
  { symbol: "EURC", name: "EURC", coingeckoId: "euro-coin", decimals: 3, rank: 99 },
  { symbol: "EUROC", name: "Euro Coin", coingeckoId: "euro-coin", decimals: 3, rank: 100 },
];
