/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AssetIdRouteImport } from './routes/asset.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronDcaAlertsRouteImport } from './routes/api/cron/dca-alerts'
import { Route as ApiCronNewsletterRouteImport } from './routes/api/cron/newsletter'
import { Route as ApiCronSnapshotsRouteImport } from './routes/api/cron/snapshots'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDcaAlertsRoute = ApiCronDcaAlertsRouteImport.update({
  id: '/api/cron/dca-alerts',
  path: '/api/cron/dca-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNewsletterRoute = ApiCronNewsletterRouteImport.update({
  id: '/api/cron/newsletter',
  path: '/api/cron/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSnapshotsRoute = ApiCronSnapshotsRouteImport.update({
  id: '/api/cron/snapshots',
  path: '/api/cron/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/asset/$id': typeof AssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/dca-alerts': typeof ApiCronDcaAlertsRoute
  '/api/cron/newsletter': typeof ApiCronNewsletterRoute
  '/api/cron/snapshots': typeof ApiCronSnapshotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/asset/$id': typeof AssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/dca-alerts': typeof ApiCronDcaAlertsRoute
  '/api/cron/newsletter': typeof ApiCronNewsletterRoute
  '/api/cron/snapshots': typeof ApiCronSnapshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/asset/$id': typeof AssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/dca-alerts': typeof ApiCronDcaAlertsRoute
  '/api/cron/newsletter': typeof ApiCronNewsletterRoute
  '/api/cron/snapshots': typeof ApiCronSnapshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/asset/$id'
    | '/api/auth/$'
    | '/api/cron/dca-alerts'
    | '/api/cron/newsletter'
    | '/api/cron/snapshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/asset/$id'
    | '/api/auth/$'
    | '/api/cron/dca-alerts'
    | '/api/cron/newsletter'
    | '/api/cron/snapshots'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/asset/$id'
    | '/api/auth/$'
    | '/api/cron/dca-alerts'
    | '/api/cron/newsletter'
    | '/api/cron/snapshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AssetIdRoute: typeof AssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDcaAlertsRoute: typeof ApiCronDcaAlertsRoute
  ApiCronNewsletterRoute: typeof ApiCronNewsletterRoute
  ApiCronSnapshotsRoute: typeof ApiCronSnapshotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/dca-alerts': {
      id: '/api/cron/dca-alerts'
      path: '/api/cron/dca-alerts'
      fullPath: '/api/cron/dca-alerts'
      preLoaderRoute: typeof ApiCronDcaAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/newsletter': {
      id: '/api/cron/newsletter'
      path: '/api/cron/newsletter'
      fullPath: '/api/cron/newsletter'
      preLoaderRoute: typeof ApiCronNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/snapshots': {
      id: '/api/cron/snapshots'
      path: '/api/cron/snapshots'
      fullPath: '/api/cron/snapshots'
      preLoaderRoute: typeof ApiCronSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AssetIdRoute: AssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDcaAlertsRoute: ApiCronDcaAlertsRoute,
  ApiCronNewsletterRoute: ApiCronNewsletterRoute,
  ApiCronSnapshotsRoute: ApiCronSnapshotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
